### ISSUE TITLE
api dót

### ISSUE THREAD

**Issue by sigurdurhaukur** [sigurdurhaukur/slysprediction#1]

**Comment by sigurdurhaukur** [comment]
google traffic [api/python library](https://dime-worldbank.github.io/googletraffic/)

**Comment by sigurdurhaukur** [comment]
ok þetta er ekki python :(

**Comment by tomasblaer** [comment]
https://github.com/mideind/Straeto

**Comment by sigurdurhaukur** [comment]
nytt verkefni
